apiVersion: v1
kind: Secret
metadata:
  name: sigma-db-credentials
  namespace: sigma
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: sigma
  password: "CHANGE_ME"
